server {
    listen ${PORT};
    server_name bbabrjced7868pqsc83u.containers.yandexcloud.net;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        log_not_found off;
    }
}